// Client-provided sample product data used by the public listing page.
// This local dataset keeps the FR1 page testable before the backend products API is ready.

export const sampleProducts = [
  {
    id: 1,
    supplier: "Supplier A",
    product_name: "Resin Bolt A D20 mm x 2.4 m",
    bolt_length: "2.4",
    bolt_diameter: "20",
    bolt_category: "Encapsulated",
    equipment_compatibility: ["Handheld", "Mechanized Bolting Machine A", "Multi-OEM"],
  },
  {
    id: 2,
    supplier: "Supplier A",
    product_name: "Resin Bolt A D22 mm x 2.4 m",
    bolt_length: "2.4",
    bolt_diameter: "22",
    bolt_category: "Encapsulated",
    equipment_compatibility: ["Handheld", "Mechanized Bolting Machine A", "Multi-OEM"],
  },
  {
    id: 3,
    supplier: "Supplier A",
    product_name: "Resin Bolt A D25 mm x 2.4 m",
    bolt_length: "2.4",
    bolt_diameter: "25",
    bolt_category: "Encapsulated",
    equipment_compatibility: ["Handheld", "Mechanized Bolting Machine A", "Multi-OEM"],
  },
  {
    id: 4,
    supplier: "Supplier A",
    product_name: "Pumpable Bolt A D20 mm x 2.4 m",
    bolt_length: "2.4",
    bolt_diameter: "20",
    bolt_category: "Encapsulated",
    equipment_compatibility: ["Handheld", "Mechanized Bolting Machine A"],
  },
  {
    id: 5,
    supplier: "Supplier A",
    product_name: "Hybrid Bolt D39 x 2.4 m",
    bolt_length: "2.4",
    bolt_diameter: "20",
    bolt_category: "Hybrid",
    equipment_compatibility: ["Handheld", "Mechanized Bolting Machine A", "Multi-OEM"],
  },
  {
    id: 6,
    supplier: "Supplier A",
    product_name: "Hybrid Bolt D46 x 2.4 m",
    bolt_length: "2.4",
    bolt_diameter: "20",
    bolt_category: "Hybrid",
    equipment_compatibility: ["Handheld", "Mechanized Bolting Machine A", "Multi-OEM"],
  },
  {
    id: 7,
    supplier: "Supplier A",
    product_name: "Hybrid Bolt B D46 x 2.4 m",
    bolt_length: "2.4",
    bolt_diameter: "20",
    bolt_category: "Hybrid",
    equipment_compatibility: ["Handheld", "Mechanized Bolting Machine A", "Multi-OEM"],
  },
  {
    id: 8,
    supplier: "Supplier A",
    product_name: "MP1 Bolt Ø20 mm x 2.2 m",
    bolt_length: "2.2",
    bolt_diameter: "20",
    bolt_category: "Encapsulated",
    equipment_compatibility: ["Handheld", "Multi-OEM"],
  },
  {
    id: 9,
    supplier: "Supplier A",
    product_name: "HC-Bolt Yielding Ø28 mm x 2.4 m",
    bolt_length: "2.4",
    bolt_diameter: "28",
    bolt_category: "Hybrid",
    equipment_compatibility: ["Handheld", "Mechanized Bolting Machine A"],
  },
  {
    id: 10,
    supplier: "Supplier A",
    product_name: "Hollow Core Bolt D28 x 2.4 m",
    bolt_length: "2.4",
    bolt_diameter: "28",
    bolt_category: "Encapsulated",
    equipment_compatibility: ["Mechanized Bolting Machine A"],
  },
  {
    id: 11,
    supplier: "Supplier A",
    product_name: "Hollow Core Bolt D32 x 2.4 m",
    bolt_length: "2.4",
    bolt_diameter: "32",
    bolt_category: "Encapsulated",
    equipment_compatibility: ["Mechanized Bolting Machine A"],
  },
  {
    id: 12,
    supplier: "Supplier A",
    product_name: "HE Bolt 2.4 m",
    bolt_length: "2.4",
    bolt_diameter: "24",
    bolt_category: "Friction",
    equipment_compatibility: ["Handheld", "Mechanized Bolting Machine A", "Multi-OEM"],
  },
  {
    id: 13,
    supplier: "Supplier A",
    product_name: "Yielding Bolt B D20 mm x 2.1 m",
    bolt_length: "2.1",
    bolt_diameter: "20",
    bolt_category: "Encapsulated",
    equipment_compatibility: ["Mechanized Bolting Machine A"],
  },
  {
    id: 14,
    supplier: "Supplier A",
    product_name: "Yielding Bolt B D20 mm x 3.0 m",
    bolt_length: "3",
    bolt_diameter: "20",
    bolt_category: "Encapsulated",
    equipment_compatibility: ["Mechanized Bolting Machine A"],
  },
  {
    id: 15,
    supplier: "Hoek",
    product_name: "Expansion shell anchored 17mm diameter steel rockbolt",
    bolt_length: "3",
    bolt_diameter: "17.28",
    bolt_category: "Encapsulated",
    equipment_compatibility: ["Handheld", "Multi-OEM"],
  },
  {
    id: 16,
    supplier: "Hoek",
    product_name: "Cement grouted 20mm diameter steel rebar",
    bolt_length: "3",
    bolt_diameter: "20",
    bolt_category: "Encapsulated",
    equipment_compatibility: ["Handheld", "Multi-OEM"],
  },
  {
    id: 17,
    supplier: "Hoek",
    product_name: "Resin grouted 20mm diameter steel rebar",
    bolt_length: "3",
    bolt_diameter: "20",
    bolt_category: "Encapsulated",
    equipment_compatibility: ["Handheld", "Multi-OEM"],
  },
  {
    id: 18,
    supplier: "Hoek",
    product_name: "Resin grouted 22mm fibreglass rod",
    bolt_length: "3",
    bolt_diameter: "22",
    bolt_category: "Encapsulated",
    equipment_compatibility: ["Handheld", "Multi-OEM"],
  },
  {
    id: 19,
    supplier: "Hoek",
    product_name: "Type SS 39 Split Set stabiliser",
    bolt_length: "3",
    bolt_diameter: "39",
    bolt_category: "Encapsulated",
    equipment_compatibility: ["Handheld", "Multi-OEM"],
  },
  {
    id: 20,
    supplier: "Hoek",
    product_name: "EXL Swellex dowel",
    bolt_length: "3",
    bolt_diameter: "26",
    bolt_category: "Encapsulated",
    equipment_compatibility: ["Handheld", "Multi-OEM"],
  },
];