# Generated by Django 4.2.29 on 2026-04-01 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bolt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("length_m", models.FloatField(help_text="Bolt length in metres")),
                (
                    "diameter_mm",
                    models.FloatField(help_text="Bolt diameter in millimetres"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Encapsulated", "Encapsulated"),
                            ("Hybrid", "Hybrid"),
                            ("Friction", "Friction"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "methodology",
                    models.CharField(
                        choices=[("Static", "Static"), ("Dynamic", "Dynamic")],
                        max_length=10,
                    ),
                ),
                ("facility", models.CharField(max_length=200)),
                (
                    "installation_method",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "encapsulation_method",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("peak_strength_kn", models.FloatField(blank=True, null=True)),
                ("yield_strength_kn", models.FloatField(blank=True, null=True)),
                ("ultimate_deformation_mm", models.FloatField(blank=True, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bolt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="bolts.bolt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaticTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bond_strength", models.FloatField(blank=True, null=True)),
                ("stiffness", models.FloatField(blank=True, null=True)),
                ("loading_rate", models.FloatField(blank=True, null=True)),
                (
                    "test",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="static_details",
                        to="bolts.test",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DynamicTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_drops", models.IntegerField(blank=True, null=True)),
                ("energy_absorption_kj", models.FloatField(blank=True, null=True)),
                (
                    "test",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dynamic_details",
                        to="bolts.test",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CurveData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("displacement_mm", models.FloatField()),
                ("load_kn", models.FloatField()),
                ("energy_absorbed_kj", models.FloatField(blank=True, null=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curve_data",
                        to="bolts.test",
                    ),
                ),
            ],
            options={
                "ordering": ["displacement_mm"],
            },
        ),
        migrations.AddField(
            model_name="bolt",
            name="equipment_compatibility",
            field=models.ManyToManyField(
                blank=True, related_name="bolts", to="bolts.equipment"
            ),
        ),
    ]
