# Generated by Django 4.2.29 on 2026-04-11 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=100)),
                ('length_m', models.FloatField(help_text='Bolt length in metres')),
                ('diameter_mm', models.FloatField(help_text='Bolt diameter in millimetres')),
            ],
        ),
        migrations.CreateModel(
            name='BoltCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EncapsulationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encapsulation_name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstallationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak_strength', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('bond_strength', models.DecimalField(blank=True, decimal_places=12, max_digits=18, null=True)),
                ('ultimate_deformation', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('stiffness', models.DecimalField(blank=True, decimal_places=12, max_digits=18, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('test_type', models.CharField(blank=True, choices=[('static', 'Static'), ('dynamic', 'Dynamic')], max_length=10, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('bolt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='bolts.bolt')),
                ('encapsulation_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bolts.encapsulationmethod')),
                ('installation_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bolts.installationmethod')),
                ('test_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bolts.testfacility')),
            ],
        ),
        migrations.CreateModel(
            name='StaticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='static_details', to='bolts.test')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_drops', models.IntegerField(blank=True, null=True)),
                ('energy_absorption_kj', models.FloatField(blank=True, null=True)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_details', to='bolts.test')),
            ],
        ),
        migrations.CreateModel(
            name='CurveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displacement_mm', models.FloatField()),
                ('load_kn', models.FloatField()),
                ('energy_absorbed_kj', models.FloatField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curve_data', to='bolts.test')),
            ],
            options={
                'ordering': ['displacement_mm'],
            },
        ),
        migrations.AddField(
            model_name='bolt',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolts', to='bolts.boltcategory'),
        ),
        migrations.AddField(
            model_name='bolt',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='bolts', to='bolts.equipmenttype'),
        ),
    ]
