# Generated by Django 4.2.29 on 2026-04-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('bolts', 'Bolts'), ('tests', 'Tests'), ('curves', 'Curves')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('file_content', models.JSONField(blank=True, null=True)),
                ('csv_content', models.TextField(blank=True, null=True)),
                ('test_id', models.IntegerField(blank=True, null=True)),
                ('records_parsed', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
